name: CI for React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Install Serve to serve the app
        run: npm install -g serve

      - name: Serve the app
        run: serve -s build

      - name: Upload build to artifact for review
        uses: actions/upload-artifact@v2
        with:
          name: production-build
          path: build/


